name: extraction
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h49ec1c0_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.1.0=py311h1ddb823_4
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h38be061_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lark=1.3.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.2=hee588c1_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.6=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.5.3=h26f9b46_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.12=h9e4cc4f_0_cpython
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.1=py311h902ca64_1
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.1.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py311h49ec1c0_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py311haee01d2_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.6.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anthropic==0.46.0
      - anyio==4.10.0
      - argcomplete==3.5.1
      - bitsandbytes==0.46.1
      - blinker==1.9.0
      - borb==2.1.25
      - cachetools==6.2.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.2
      - click==8.3.0
      - cloudpickle==3.1.1
      - cobble==0.1.4
      - cryptography==44.0.3
      - cssselect2==0.8.0
      - curlify==2.2.1
      - dicttoxml==1.7.16
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dunamai==1.25.0
      - ebooklib==0.18
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - filetype==1.2.0
      - fonttools==4.59.0
      - fsspec==2025.3.2
      - ftfy==6.3.1
      - genson==1.3.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - google-genai==1.40.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - identify==2.6.15
      - jiter==0.11.0
      - joblib==1.5.2
      - json-repair==0.48.0
      - json5==0.12.0
      - jsonpath-ng==1.7.0
      - loguru==0.7.3
      - lxml==5.4.0
      - mammoth==1.11.0
      - markdown-it-py==3.0.0
      - markdown2==2.5.4
      - markdownify==1.2.0
      - marker-pdf==1.10.1
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - narwhals==2.6.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - ollama==0.6.0
      - openai==1.109.1
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - outlines==1.2.5
      - outlines-core==0.2.11
      - pandas==2.3.3
      - pdfminer-six==20250327
      - pdfplumber==0.11.6
      - pdftext==0.6.3
      - pillow==10.4.0
      - ply==3.11
      - poetry-dynamic-versioning==1.9.1
      - pre-commit==4.3.0
      - protobuf==6.32.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pydeck==0.9.1
      - pydyf==0.11.0
      - pygments==2.19.1
      - pymupdf==1.26.3
      - pypdfium2==4.30.0
      - pyphen==0.17.2
      - pytesseract==0.3.13
      - python-barcode==0.15.1
      - python-dateutil==2.6.1
      - python-dotenv==1.1.1
      - python-pptx==1.0.2
      - pyyaml==6.0.2
      - qrcode==8.2
      - rapidfuzz==3.14.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - smmap==5.0.2
      - streamlit==1.50.0
      - streamlit-ace==0.1.1
      - surya-ocr==0.17.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tinyhtml5==2.0.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.7.0
      - tqdm==4.67.1
      - transformers==4.56.2
      - triton==3.3.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.2.3
      - vastai==0.3.1
      - virtualenv==20.34.0
      - watchdog==6.0.0
      - weasyprint==63.1
      - websockets==15.0.1
      - xdg==6.0.0
      - xlsxwriter==3.2.9
      - zopfli==0.2.3.post1
prefix: /home/tux/miniforge3/envs/extraction
